language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run effective_manager sh -c "python effective_manager/manage.py test && flake8"
