version: "3"

services:
  effective_manager:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./effective_manager:/effective_manager
    command: >
      sh -c "python effective_manager/manage.py runserver 0.0.0.0:8000"