# Generated by Django 2.1.7 on 2019-03-30 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=120, verbose_name='Town')),
                ('street', models.CharField(max_length=120, verbose_name='Street')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='House number')),
                ('apartment_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Apartment number')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First name')),
                ('surname', models.CharField(max_length=120, verbose_name='Surname')),
                ('description', models.TextField(verbose_name='Description')),
                ('avatar', models.ImageField(upload_to='images/avatars')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='certificates.Address', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'People',
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('email_type', models.PositiveSmallIntegerField(choices=[(1, 'Home'), (2, 'Work')], verbose_name='Email type')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Group name')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number format: '+## ### ### ###'", regex='^\\+?\\d{2}? ?(\\d{3}?(-| )?){3}$')], verbose_name='Phone number')),
                ('phone_type', models.PositiveSmallIntegerField(choices=[(1, 'Cellphone'), (2, 'Home'), (3, 'Work')], verbose_name='Phone type')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.Client', verbose_name='Client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, to='certificates.Group', verbose_name='Groups'),
        ),
    ]
