# Generated by Django 2.1.7 on 2019-03-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='client',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='client',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['surname', 'first_name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='client',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
