# Generated by Django 2.1.7 on 2019-03-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_client_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=120, verbose_name='Town')),
                ('street', models.CharField(max_length=120, verbose_name='Street')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='House number')),
                ('apartment_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Apartment number')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='avatar',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='certificates.Address', verbose_name='Address'),
        ),
    ]
