# Generated by Django 2.1.7 on 2019-03-30 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0004_auto_20190330_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.CharField(max_length=7)),
                ('added_to_database', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to_poller_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to_certificator_date', models.DateTimeField(blank=True, null=True)),
                ('certificator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.Client')),
                ('poller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
