# Generated by Django 2.1.7 on 2019-03-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_auto_20190330_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='apartment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Apartment number'),
        ),
        migrations.AddField(
            model_name='client',
            name='house_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='House number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='street',
            field=models.CharField(default='Nowa', max_length=120, verbose_name='Street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='town',
            field=models.CharField(default='Wrocław', max_length=120, verbose_name='Town'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
