# Generated by Django 2.1.7 on 2019-03-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author2',
            new_name='author',
        ),
    ]
